kind: pipeline
name: startpageredux
type: docker
steps: 
  - 
    commands: 
      - yarn
    image: "node:alpine"
    name: deps
  - 
    commands: 
      - "yarn build"
    image: "node:alpine"
    name: build
  - 
    name: copyfiles
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: HOST
      port: 22
      key:
        from_secret: SSH_KEY
      source: dist
      target: ~/apps/redux
      username:
        from_secret: USER

#- name: deploy
#  image: appleboy/drone-ssh
#  host: ${HOST}
#  user: ${USER}
#  key: ${SSH_KEY}
#  port: 22

